### ISSUE TITLE
Shortcut to add checklist does not wokr

### ISSUE THREAD

**Issue by ichaudry** [Automattic/simplenote-macos#665] opened 2020-09-04 17:52 UTC
### Description
The shortcut for add checklist just does not work on Mac

MacBook Pro 2017, macOS Catalina, Version 10.15.6

Using simple note version 2.0

**Comment by jleandroperez** [comment] 2020-09-04 17:59
Hi there @ichaudry,

I'm afraid I can't reproduce on my end. Would it be possible to get a sample video? perhaps there's something else we're missing.

Thanks in advance!

**Comment by jleandroperez** [comment] 2020-09-11 13:31
Closing as cannot reproduce. If needed, please feel free to reopen with as many extra details as possible.

Thank you!

**Closed by jleandroperez** 2020-09-11 13:31 UTC
Labels: bug
