### ISSUE TITLE
Toggle sidebar setting not maintained when quitting and re-opening app

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-macos#165] opened 2018-01-03 12:42 UTC
If you hide the sidebar in the app and then quit the app and re-open it the side bar is visible again.

![toggle](https://user-images.githubusercontent.com/7946521/34521043-8433de98-f083-11e7-83e1-f4248f1eb865.png)

Is it possible to have the app remember that the sidebar was hidden last time it was used?

Reported in 872949-zen

**Comment by eduardozulian** [comment] 2018-01-04 11:36
Another report on 877142-zen

**Comment by roundhill** [comment] 2018-01-18 16:52
This is a dupe of https://github.com/Automattic/simplenote-macos/issues/163

**Closed by roundhill** 2018-01-18 16:52 UTC
Labels: duplicate
