### ISSUE TITLE
Switching from Dark to Light mode removes checkboxes

### ISSUE THREAD

**Issue by fstath** [Automattic/simplenote-macos#563] opened 2019-08-23 14:54 UTC
When switching from Dark to Light mode in macOS the checklist's checkboxes disappear.

Screencast:
![Screen Capture on 2019-08-23 at 17-47-43](https://user-images.githubusercontent.com/32326882/63601711-a2656680-c5ce-11e9-8a55-8c89379eba33.gif)

MacBookPro | macOS 10.14.5 | Simplenote 1.6.1

Reported on Twitter: https://twitter.com/DesignICU/status/1164900463122231297

**Comment by codebykat** [comment] 2020-06-18 21:40
Oh I can't reproduce this now and I see the theme issue is reported in https://github.com/Automattic/simplenote-macos/issues/564, so closing!

**Closed by codebykat** 2020-06-18 21:40 UTC
