### ISSUE TITLE
Title sometimes disappears when syncing between Mac and iOS

### ISSUE THREAD

**Issue by zandyring** [Automattic/simplenote-macos#199] opened 2018-03-26 18:11 UTC
Customer in zen-1033279 has found that when he creates a note with just a title (no content) in his Mac app, then closes it and goes to iOS, sometimes the note says just "new title" rather than the title. He has to go to his Mac app again, and hit enter on the note to get it to sync properly.

I wasn't able to reproduce, but did ask him for further information in the ticket.

Chatted about it here, as well: p1522087215000727-slack-C02FMH4G8 (edited for public repo).

**Comment by pauljacobson** [comment] 2018-03-30 12:21
The user returned with feedback:

>I’m not sure if pressing Enter after creating a new note or not has an impact. In both situations what I did was close the Simplenote Mac app quickly after I had made my last change. So what it appears is that for some reason not all changes are getting sync’d to server before the app is killed. Otherwise this actually seems to be working a bit more reliably for me today than it has in the past few weeks.
>
>I’m running public betas of 10.13.4 on my Mac (latest one) and iOS 11.3 on my iPhone. Simplenote versions are 1.3.2 on the Mac and whatever the latest iOS version is (couldn’t find the number).

**Comment by jleandroperez** [comment] 2020-06-11 00:23
Closing as cannot reproduce. Simplenote 1.11 / macOS Catalina.

Please feel free to reopen if needed. Thank you!

**Closed by jleandroperez** 2020-06-11 00:23 UTC
Labels: [feature] sync, bug
