### ISSUE TITLE
Last Window Dismiss Behavior

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-macos#111] opened 2017-01-16 16:05 UTC
We've got some feedback in our last release, from the Apple Team, indicating that after dismissing the last window, there was no way to re-create it.

As a quick workaround, i've proceeded to revert to our old behavior: whenever you close the main window, the process will get terminated.

Let's figure out a proper way to allow users to reopen the main window, and bring back the old 'backgrounding' behavior.

**Comment by drw158** [comment] 2017-01-16 16:35
Thanks @jleandroperez 

I looked at some other apps. Most just have a menu item with the name of the app under the Window menu. Some have a shortcut, some don't.

I suggest just a new menu item, simply named "Simplenote" with no shortcut under the Window menu.

We could use "Simplenote App" to be more descriptive if we want to. That describes the window more.

I found a strange behavior while looking at this. First, close the SN window then click on New Note in the Note menu. It does create a new note, but it doesn't open the app window, which is unexpected. I'd say that's a bug.

Perhaps just opening the window for "New Note" would appease Apple?

**Comment by ashercantrell** [comment] 2017-01-21 18:43
We've gotten a few user complaints about this, as they preferred the backgrounding behavior. One user in particular is having a problem with it where it makes her sign back into Simplenote every time she closes the app. #3016988-t

**Comment by eduardozulian** [comment] 2017-12-20 12:07
From what I see, it's the same that happens on 858826-zen.

Once you hit the red close button on the Mac app, Simplenote:

1. Closes completely and vanishes from the Dock. 
2. Logs out of the user's account

I was able to reproduce nº 1 on my Mac – Version 1.1.8 (1182). However, nº 2 didn’t happen here.

**Comment by bummytime** [comment] 2019-05-15 20:53
**Update 5/14/2019 →** Tested in Simplenote 1.4.2 on macOS 10.14.4 (Mojave) and I am currently seeing what I expect:

* Pressing the close (red) button closes the window and the app remains running.
* I see an option to reopen the main window under `Window→Main Window` (which works)
* Clicking on the already running Dock icon brings up the main window (closed or not)
* At no time am I logged out of the app.

So closing this issue because of that ☝️. Feel free to reopen if you disagree.

**Closed by bummytime** 2019-05-15 20:53 UTC
Labels: enhancement
