### ISSUE TITLE
Checkboxes on current note deleted when theme is changed

### ISSUE THREAD

**Issue by potahto** [Automattic/simplenote-macos#422] opened 2019-12-19 15:23 UTC
Changing from Light to Dark or Dark to Light deletes checkboxes.

To reproduce: 
1. Create a note with a checkbox.
2. Switch themes.

Expected Result: Note content is preserved.
Actual Result: Checkboxes (widgets/characters) are deleted.

Tested on Simplenote 1.8, macOS 10.14.6 Mojave.

Demonstration: https://streamable.com/qxp4j

**Comment by msilbers** [comment] 2019-12-20 18:41
closing for duplicate of #321

**Closed by msilbers** 2019-12-20 18:41 UTC
