### ISSUE TITLE
Mac OSX: cut and pasting does not keep checklist formatting

### ISSUE THREAD

**Issue by infrontofthepark** [Automattic/simplenote-macos#519] opened 2020-04-26 09:23 UTC
Cut and pasting a checklist results in losing its formatting.

### Expected
It is expected that the checklist format will be maintained when cut and pasting.

### Observed
The checkboxes are lost.

### Reproduced
> 1. Create several items and transform into a checklist
> 2. Cut and paste elsewhere in the same or another note
> 3. The formatting is lost

[bug.mov.zip](https://github.com/Automattic/simplenote-macos/files/4535002/bug.mov.zip)

***(Optional)*** If you reproduced the bug on a specific system, please replace SYSTEM_MAKE, SYSTEM_MODEL, MACOS_VERSION, and APP_VERSION below with the details for that system.  If you reproduced the bug on multiple systems, please add a row for each system.

Make|Model|macOS Version|App Version
-|-|-|-
SYSTEM_MAKE|SYSTEM_MODEL|10.14.6|1.10.0

**Comment by jleandroperez** [comment] 2020-04-28 23:01
Closing as duplicate of #307

Definitely on our radar, we'll get this one fixed soon. Thanks for reaching out!!

**Closed by jleandroperez** 2020-04-28 23:01 UTC
Labels: bug
