### ISSUE TITLE
Markdown list nesting stops working after 5 levels

### ISSUE THREAD

**Issue by markbiek** [Automattic/simplenote-macos#1069] opened 2022-07-27 14:31 UTC
### Expected
I had a Markdown list (using `-`) which had 7 levels of nesting and I expected to see the text for each level when viewing the rendered version of the note.

### Observed
I see the bullet point for level 6 but no text and the level 7 bullet point doesn't appear at all

### Reproduced
Enter a deeply nested list like the following:
```
- Level 1
	- Level 2
		- Level 3
			- Level 4
				- Level 5
					- Level 6
						- Level 7
```

I also tried with additional formatting to see if that made a difference and got the same results.
```
- **Bold text**
	- **Bold text**
		- **Bold text**
			- **Bold text**
				- **Bold text**
					- **Bold text**
					- Regular text
					- _Italic text_
						- Regular text
```

** Markdown **
![image](https://user-images.githubusercontent.com/917632/181273412-9f6d367c-f26e-4e10-b71a-55e4e6535a93.png)

** Rendered **
![image](https://user-images.githubusercontent.com/917632/181273468-797cff5c-37f8-4182-8451-31f24d87ea6e.png)

### System Info

MacBook Pro (13", M1, 2020)|12.2.1|2.17

**Comment by charliescheer** [comment] 2024-01-19 23:21
Duplicate of #1020

**Closed as completed by charliescheer** 2024-01-19 23:21 UTC
Labels: bug, [Type] Bug
