### ISSUE TITLE
Unable to highlight search term on the search bar after an initial search

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-macos#897] opened 2021-03-04 02:06 UTC
It was reported in 3782923-zen that it was impossible to highlight the search term by double-clicking it or drag-to-select after performing a search on the app.

The user also notice this happens only on Big Sur.

### Expected

I would expect to be able to highlight the search term by double-click or drag-to-select so I can remove it with a single Delete key for another search.

### Observed

I wasn't able to highlight the search term

### Reproduced

1. Enter a search term on the search box
2. Click on any note in the returned search result
3. Double-click or drag-to-select the search term on the search box and notice the highlight doesn't stay

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.

![Screen Capture on 2021-03-04 at 10-01-11](https://user-images.githubusercontent.com/40906847/109899327-a77d9880-7cd0-11eb-8336-db48a3abbdce.gif)

***(Optional)*** If you reproduced the bug on a specific system, please replace SYSTEM_MAKE, SYSTEM_MODEL, MACOS_VERSION, and APP_VERSION below with the details for that system.  If you reproduced the bug on multiple systems, please add a row for each system.

Make|Model|macOS Version|App Version
-|-|-|-
Apple|iMac (Retina 5K, 27-inch, 2019)|Big Sur 11.2.2 (20D80)|2.8

**Comment by pachlava** [comment] 2021-03-04 08:53
@reginabally thank you! I can reproduce this too, it looks like this works every 2nd time, as soon as the search bar is focused.

MBP 16 | Bug Sur 11.2 | Simplenote 2.8

**Comment by jleandroperez** [comment] 2021-03-09 12:46
Closing as duplicate, in favor of #880

Thanks everyone!!

**Closed as completed by jleandroperez** 2021-03-09 12:46 UTC
Labels: bug, [feature] search
