### ISSUE TITLE
Markdown Preview with System Appearance showing white text on white background

### ISSUE THREAD

**Issue by genthaler** [Automattic/simplenote-macos#610] opened 2020-07-24 04:40 UTC
When theme is 'System Appearance', Markdown Preview displays white text on white background, except for triple-back-tick code blocks. If theme is Light or Dark, Markdown Preview displays as expected.

### Expected
***(Required)*** Add a concise description of what you expected.

### Observed
When theme is 'System Appearance', Markdown Preview displays white text on white background, except for triple-back-tick code blocks. If theme is Light or Dark, Markdown Preview displays as expected.

### Reproduced

Select View > Theme > System Appearance

Create a note with:

Now is the time
For all good men
```
To come
To the aid
Of their party
```

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.

![image](https://user-images.githubusercontent.com/94579/88361031-084c0680-cdbb-11ea-8f6a-b9225e148186.png)

![image](https://user-images.githubusercontent.com/94579/88361042-1863e600-cdbb-11ea-9128-12df2c99ddd0.png)

***(Optional)*** If you reproduced the bug on a specific system, please replace SYSTEM_MAKE, SYSTEM_MODEL, MACOS_VERSION, and APP_VERSION below with the details for that system.  If you reproduced the bug on multiple systems, please add a row for each system.

Apple MacBookAir 2020 | Mac OS X 10.15.6 | Simplenote 1.11.1

**Comment by jleandroperez** [comment] 2020-08-11 23:15
Hi there @genthaler,

Thank you for reaching out! I'm afraid I'm unable to reproduce this issue on my end. Would it be possible to retest on the latest build? (1.12).

Exact steps I'm following are:

1. Switch macOS to Light Mode
2. Switch Simplenote to `System Appearance`
3. Add a new note with the content pasted below
4. Switch to Markdown Preview


Thanks in advance!


----

Now is the time
For all good men

```
To come
To the aid
Of their party
```

**Comment by jleandroperez** [comment] 2020-09-08 19:23
Closing this one as cannot repro. Simplenote 2.2.

**Please** reopen if needed, any extra steps would be more than welcome.

Thank you!

**Closed by jleandroperez** 2020-09-08 19:23 UTC
Labels: bug

**Comment by genthaler** [comment] 2020-09-09 20:47
Hi @jleandroperez , I can confirm it's working on latest update from the Mac App Store. Sorry for not replying earlier, I missed the notification.

**Comment by jleandroperez** [comment] 2020-09-09 21:30
No worries at all! thank you for the update @genthaler 😄 

And thank you for helping us improve the app!!
