### ISSUE TITLE
[Question] How to enable Markdown on MacOs

### ISSUE THREAD

**Issue by vpakg** [Automattic/simplenote-macos#115] opened 2017-02-08 16:51 UTC
I've been using simplenote on linux for a while. I Also own a Macbook and I'm switching from a Linux to iMac at work, but I'm missing some key features like how to switch to Markdown. It's quite easy to find it on linux, but I can find it anywhere on mac. 

Is this feature missing or am I just not finding it? If it's missing, are there plans to implement it?

Thank you!

**Comment by roundhill** [comment] 2017-02-08 16:57
You can't use Markdown on the app at this time.

Closing as duplicate of #73

**Closed by roundhill** 2017-02-08 16:57 UTC
Labels: duplicate
