### ISSUE TITLE
Checklist completed "check" rendering upside down after update to 1.8

### ISSUE THREAD

**Issue by ericnentrup** [Automattic/simplenote-macos#424] opened 2019-12-19 18:12 UTC
After updating from 1.7 to 1.8, checkbox in the completed state renders the check mark upside down.

### Expected

1. Create a note and insert a checklist.
2. Check off completed item
3. Receive a standard, up-facing check mark for completed items

### Observed
1. Create a note and insert a checklist.
2. Check off completed item
3. Receive a upside down checkmark for completed items

### Reproduced
1. Create a note and insert a checklist.
2. Check off completed item
3. Receive a upside down checkmark for completed items

**Comment by theck13** [comment] 2019-12-19 18:14
This is a duplicate of https://github.com/Automattic/simplenote-macos/issues/401.

**Closed by theck13** 2019-12-19 18:14 UTC
Labels: bug
