### ISSUE TITLE
NSLayoutManager: Loop / Crash when moving app to different monitor

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#50] opened 2016-08-11 16:23 UTC
<a href="https://github.com/jleandroperez"><img src="https://avatars.githubusercontent.com/u/1195260?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jleandroperez](https://github.com/jleandroperez)**
_Friday Sep 25, 2015 at 15:25 GMT_

---

The app appears to be crashing (randomly), in a recursive NSLayoutManager loop. One of our (awesome) users provided the crashlogs, [available here](https://cloudup.com/ceFK2EGhkGs).

Sadly, no single Simplenote-Exclusive line seems to get executed (in that loop call). Let's dig deeper!

**Comment by dabeeeenster** [comment] 2016-08-31 18:37
I have found a way to reliably recreate this issue (or something related to this issue). I use https://github.com/jigish/slate with a config file that resizes the windows when I plug or unplug a second monitor. Whenever I plug in a second monitor it crashes the app when I have slate running. 

My .slate is here https://gist.github.com/dabeeeenster/c14d32ce21a80294a41fd12e5362e053

**Comment by catkit** [comment] 2016-10-28 00:27
Another user reported similar issue: #2894226-t Steps to reproduce:

- Have laptop closed and running through an external Thunderbolt display
- Have a dozen or so apps open
- Command+Tab to Simple note to begin typing
- Simplenote frozen, not responding to mouse or keyboard
- Command+Q to quit
- Relaunch and all is well

Simplenote Version 1.1.4
OSX 10.11.5
Macbook Pro, connected to Thunderbolt display

**Comment by eduardozulian** [comment] 2016-11-24 13:33
Another report on 2931988-t. Still waiting for more info.

**Comment by dromero20** [comment] 2016-12-09 20:53
Similar issue regarding the moving from Retina to non-Retina monitor.
2952421-t
To replicate:

- Macbook pro retina with an external non retina monitor.
- Open simplenote on the retina display
- Drag it to the non retina external display

**Comment by kevmarsden** [comment] 2016-12-10 01:15
Another report in 2951140-t

Steps from the user: 

> Start Simplenote on Macbook
> create a new note - just enter a title or not.
> Then drag Simplenote to second monitor
> hit enter within Simplenote and then it closes down.

**Comment by kevmarsden** [comment] 2017-02-03 18:35
Another report in 3038729-t

It crashes when they start typing or when trying to paste text into Simplenote (when it's displayed in the external monitor).  

Details from user:

> Simplenote  1.1.8
> 
> I’m running a 12” Macbook with MacOS 10.12.3
> 
> I’m using both the Macbook screen and one external monitor (not mirrored).

**Comment by sandymcfadden** [comment] 2017-02-10 15:07
Another report here 3052946-t

>Simplenote 1.1.8 and MacOS 10.12.3
> It reproduces only when Simplenote window is initially opening into retina display

**Comment by scottrblock** [comment] 2017-05-12 12:54
Can confirm this is happening to me too. Same steps to reproduce with dragging from retina to non-retina.

**Comment by rachelsquirrel** [comment] 2017-06-28 10:26
Also reported in #3276487-t with latest Mac OS

**Comment by yayitswei** [comment] 2017-09-23 00:23
Is there a estimated timeline for a fix?

**Comment by rwaynick** [comment] 2017-10-02 20:36
Another in, 713340-zen.

> Every time I connect my laptop to a TV with an HDMI cable, SimpleNote crashes
> Macbook Pro (Early 2015 version) and macOS Sierra.

_Asking for more details in ticket._

**Comment by orrd** [comment] 2017-10-25 19:30
Any time estimate for a fix?  A year and half is a long time to have a major and easily reproducible bug in an active commercial app go unfixed.

**Comment by orrd** [comment] 2017-10-25 19:32
Any time estimate for a fix? It should be easily reproducible since the crash happens consistently every time anyone with non-Retina monitors tries to move the app to a non-Retina screen.  It seems like this should be an easy bug to reproduce and fix.

**Comment by kevmarsden** [comment] 2017-12-14 23:27
Another report in 845570-zen

Steps reported by user:

> 1. Start SimpleNote on my MBP with a Retina screen. 
> 2. Close the laptop. 
> 3. Connect it to an external screen (set as primary monitor so all apps switch over to new screen) 
> 4. Wake up the laptop

**Comment by orrd** [comment] 2017-12-14 23:44
Yeah, SimpleNote knows how to reproduce it, they just aren't bothering to take the time to fix it.  There hasn't been a release of the macOS SimpleNote app since January, so it seems to be just not maintained any more.

**Comment by roundhill** [comment] 2017-12-14 23:56
> so it seems to be just not maintained any more

Update coming in a few weeks :)

I haven't been able to reproduce this using the current develop branch. So hopefully the issue will be resolved for everyone when the next update is out.

**Comment by roundhill** [comment] 2017-12-22 19:47
Can y'all please test the 1.2.0 release to see if it fixes the issue for you?

**Comment by orrd** [comment] 2018-01-03 22:24
I'm on 1.1.1 now, and it seems to no longer be crashing when moving between monitors.  Was the fix also in 1.1.1?

**Comment by jaymendoza** [comment] 2018-01-14 22:22
@roundhill Confirmed as fixed for me on 1.2 (1200).

I was experiencing the issue on 1.1.8 (1182).

**Comment by jleandroperez** [comment] 2018-01-23 15:53
@orrd This was a macOS SDK bug (from what we can tell, fixed in High Sierra (10.13). 

The fix should only be in 1.2.0, since previous builds were linking macOS Sierra (10.12)'s SDK.

Closing this one, thanks everyone!

**Closed by jleandroperez** 2018-01-23 15:53 UTC
