### ISSUE TITLE
All Text Turned to Links

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-macos#448] opened 2020-01-22 19:05 UTC
So far we have two reports, both on OSX Catalina 10.15.2, that all text in all notes has turned into a link. I cannot reproduce this and am awaiting more details.

Logging out and back in does not resolve the issue.

macOS Version|App Version
-|-
Catalina Version 10.15.2 (19C57) | 1.9

reported in #2650881-zen and #2649989-zen

**Comment by rezzap** [comment] 2020-01-24 12:16
I have another report of this here: 2656764-zen

I'm asking for additional details.

**Comment by sarahfg** [comment] 2020-01-26 18:59
> looked at the most recent notes: they were fine! Then I looked at one added a few days ago, and it was all links. Returning to the newer notes, they now all displayed as links again. 

User has logged in and out, as well as trying to completely uninstall and reinstall the app 

#2649989-zen

**Comment by sarahfg** [comment] 2020-01-27 20:06
>Anytime I restart Simplenote and the notes appear properly, if I click on 3 different notes, the 4th note appears as all links.

#2649989-zen

The same user has repeated issue on Catalina and v1.9 of Simplenote

**Comment by msilbers** [comment] 2020-01-28 17:25
reported in #2665217-zen

**Comment by msilbers** [comment] 2020-01-28 18:14
reported in #2666678-zen

**Comment by sarahfg** [comment] 2020-01-29 16:53
The user in this ticket #2669271-zen says it happens if they begin notes with links. I've tested but can't reproduce. They will hopefully write back with some exact text we can test with.

**Comment by sarahfg** [comment] 2020-01-29 20:38
I was able to reproduce based on that user's info! 

1. Create a note with just the URL in it, no title, no text
2. Click into that note
3. Click into any other note. That note will become a link

![](https://d.pr/i/Cz2Pav+)

(Image link: https://d.pr/i/Cz2Pav )

**Comment by rezzap** [comment] 2020-01-30 09:43
Another report with useful information here:

Mac OS 10.13.6
SimpleNote 1.9

"Scrolling down the notes list everything is fine until I hit a note which as an URL as the title - then every note in the list, above and below, suddenly becomes a live link leading to the URL in the URL-titled note."

2669533-zen

**Comment by rezzap** [comment] 2020-01-30 10:34
Another report:

2670413-zen

" I'm writing because Simplenote on my iMac has inexplicably converted all of the text on all of my notes into a hyperlink (to a link that was posted in a recent note). The problem does not exist on my Macbook Pro or my iPhone."

**Comment by samuelbalogh** [comment] 2020-01-30 16:52
I can reproduce the same issue:

- Given that I create a note with a hyperlink as the title,
- Then I see that all other notes are converted into that hyperlink.

macOs Mojave 10.14.6

**Comment by codebykat** [comment] 2020-02-04 18:28
This should've been closed by #453, not sure why the GitHub magic didn't work.

**Closed by codebykat** 2020-02-04 18:28 UTC
Labels: [priority] high, bug

**Comment by jleandroperez** [comment] 2020-02-04 18:34
Thank you @codebykat ❤️
